language: python
python:
    - "2.7"
install:
    - pip install pipenv --upgrade
    - pipenv install 
    - pip install codecov
script:
    - coverage run main_test.py
after_success:
      - codecov
